FROM python:3.8

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY api .
COPY authentication .
COPY categories .
COPY products .
COPY providers .
COPY manage.py .

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
